export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_LOADINGS = 'SET_LOADINGS'
export const DISMISS_LOADING = 'DISMISS_LOADING'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR'
export const GET_PRODUCTS_ERROR = 'PRODUCT_DELETE_ERROR'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE'
export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT'


